{% set name = "wirerope" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/youknowone/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ddac3e17a36f95088c815be27e5841c7278989c6a3a6852993921374017be1f8

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - six >=1.11.0

test:
  imports:
    - wirerope
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/youknowone/wirerope
  summary: Turn functions and methods into fully controllable objects
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: WireRope is a wrapper interface for python callable.
  description: |
    wirerope.rope.WireRope is the wrapper for callables. By wrapping a function with WireRope with a custom subclass of
    the wirerope.wire.Wire class, the wire object will be created by each function or bound method.
  doc_url: https://wirerope.readthedocs.io
  dev_url: https://github.com/youknowone/wirerope

extra:
  recipe-maintainers:
    - boldorider4
